spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myselectshop
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  secret:
    key: {SECRET_KEY}
naver:
  client:
    id: {NAVER_CLIENT_ID}
    secret: {NAVER_CLIENT_SECRET}
---
# ?? ???
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{DB_HOST}
    username: {DB_USER}
    password: {DB_PASSWORD}